### ISSUE TITLE
Uncaught (in promise) TypeError: this.setMap is not a function

### ISSUE THREAD

**Issue by Ladvace** [Fl4m3Ph03n1x/marker-cluster-polygon#1]
I'm following the code here: https://github.com/Fl4m3Ph03n1x/marker-cluster-polygon/blob/master/js/myscript.js.

but when I call the library MarkerManager I got the following error: 

![image](https://user-images.githubusercontent.com/31326058/134888629-3a5614d9-ec74-40b6-8f61-5230b3fe7b17.png)

**Comment by Fl4m3Ph03n1x** [comment]
This project is unfortunately not being maintained currently. 
The issue seems to be with the library the code depends on, I advise you have a look there. 
Other than that, I can't help you anymore.
